Repository frigid14/frigid, pull requests merged in 2022-09, with the labels that each got.

#3 Overhaul Frigid (map)
  Resources/Locale/en-US/administration/ui/admin-announce-window.ftl
  Resources/Locale/en-US/communications/communications-console-component.ftl
  Resources/Locale/en-US/job/job-names.ftl
  Resources/Maps/frigid.yml
  Resources/Prototypes/Entities/Structures/Doors/MaterialDoors/material_doors.yml
  Resources/Prototypes/Parallaxes/test.yml
  Resources/Prototypes/Roles/Jobs/Civilian/bartender.yml
  Resources/Prototypes/Roles/Jobs/Civilian/chef.yml
  Resources/Prototypes/Roles/Jobs/Civilian/farmer.yml
  Resources/Prototypes/Roles/Jobs/departments.yml
  Resources/Prototypes/Tiles/plating.yml
  Resources/Prototypes/_Frigid/Entities/Markers/Spawners/zeds.yml
  Resources/Prototypes/_Frigid/Entities/Structures/Doors/airlocks.yml
  Resources/Prototypes/_Frigid/Entities/Structures/Doors/doors.yml
  Resources/Prototypes/_Frigid/Maps/frigid.yml
  Resources/Prototypes/_Frigid/Parallaxes/snow.yml
  Resources/Textures/_Frigid/Structures/Doors/metaldoor.rsi/closed.png
  Resources/Textures/_Frigid/Structures/Doors/metaldoor.rsi/closing.png
  Resources/Textures/_Frigid/Structures/Doors/metaldoor.rsi/meta.json
  Resources/Textures/_Frigid/Structures/Doors/metaldoor.rsi/metal_padlock.png
  Resources/Textures/_Frigid/Structures/Doors/metaldoor.rsi/open.png
  Resources/Textures/_Frigid/Structures/Doors/metaldoor.rsi/opening.png
  Resources/Textures/_Frigid/Structures/Doors/roomdoor.rsi/closed.png
  Resources/Textures/_Frigid/Structures/Doors/roomdoor.rsi/closing.png
  Resources/Textures/_Frigid/Structures/Doors/roomdoor.rsi/meta.json
  Resources/Textures/_Frigid/Structures/Doors/roomdoor.rsi/open.png
  Resources/Textures/_Frigid/Structures/Doors/roomdoor.rsi/opening.png
  Resources/Textures/_Frigid/Structures/Doors/roomdoor.rsi/room_padlock.png
Labels: Changes: Sprites, Changes: Map, No C#

#6 New Life Rule
  Resources/Server Info/Rules.txt
Labels: No C#

#7 Bandaid fix radios
  Resources/Prototypes/Entities/Objects/Devices/radio.yml
Labels: No C#

#12 Hotfix client blackscreen
  Resources/Prototypes/Roles/Jobs/departments.yml
Labels: No C#

#15 Frigidifies Frigid
  Resources/Locale/en-US/job/job-names.ftl
  Resources/Maps/frigid.yml
  Resources/Prototypes/Entities/Clothing/Back/duffel.yml
  Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_bottles.yml
  Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_cans.yml
  Resources/Prototypes/Entities/Objects/Misc/space_cash.yml
  Resources/Prototypes/Entities/Objects/Vehicles/buckleable.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/LMGs/lmgs.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Launchers/launchers.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Pistols/pistols.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Revolvers/revolvers.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Rifles/rifles.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/SMGs/smgs.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml
  Resources/Prototypes/Entities/Structures/Wallmounts/Signs/posters.yml
  Resources/Prototypes/Parallaxes/test.yml
  Resources/Prototypes/Recipes/Construction/Graphs/structures/girder.yml
  Resources/Prototypes/Roles/Jobs/Engineering/mechanic.yml
  Resources/Prototypes/Roles/Jobs/Engineering/station_engineer.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_doctor.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml
  Resources/Prototypes/Roles/Jobs/Science/chemist.yml
  Resources/Prototypes/Roles/Jobs/Science/scientist.yml
  Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
  Resources/Prototypes/Roles/Jobs/Security/military.yml
  Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
  Resources/Prototypes/Roles/Jobs/departments.yml
  Resources/Prototypes/Tiles/floors.yml
  Resources/Prototypes/Tiles/plating.yml
  Resources/Prototypes/_Frigid/Entities/Clothing/Belt/holster.yml
  Resources/Prototypes/_Frigid/Entities/Markers/Spawners/jobs.yml
  Resources/Prototypes/_Frigid/Entities/Markers/Spawners/zeds.yml
  Resources/Prototypes/_Frigid/Entities/Structures/Walls/grille.yml
  Resources/Prototypes/_Frigid/Maps/frigid.yml
  Resources/Prototypes/_Frigid/Parallaxes/snow.yml
  Resources/Textures/Interface/Misc/job_icons.rsi/Soldier.png
  Resources/Textures/Interface/Misc/job_icons.rsi/meta.json
Labels: Changes: Sprites, Changes: Map, No C#

#18 Attempt to fix tests
  Resources/Audio/Lobby/attributions.yml
  Resources/Locale/en-US/tools/tool-qualities.ftl
  Resources/Prototypes/Entities/Objects/Tools/cowtools.yml
  Resources/Prototypes/Roles/Jobs/Civilian/chaplain.yml
  Resources/Prototypes/Roles/Jobs/Command/centcom_official.yml
  Resources/Prototypes/Roles/Jobs/departments.yml
  Resources/Prototypes/tool_qualities.yml
Labels: No C#

#21 Fix tests 2: Electric Boogalo
  Resources/Maps/infiltrator.yml
  Resources/Prototypes/Catalog/Fills/Backpacks/duffelbag.yml
  Resources/Prototypes/Catalog/Fills/Items/belt.yml
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Entities/Clothing/Belt/belts.yml
  Resources/Prototypes/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml
  Resources/Prototypes/Maps/infiltrator.yml
  Resources/Prototypes/Roles/Jobs/Civilian/reporter.yml
  Resources/Prototypes/Roles/Jobs/Medical/psychologist.yml
  Resources/Prototypes/_Frigid/Entities/Objects/Tools/welder_fuel.yml
  Resources/Prototypes/tags.yml
Labels: Changes: Map, No C#

#20 Disable station events
  Resources/Prototypes/game_presets.yml
Labels: No C#

#22 UI Changes
  Content.Client/Administration/AdminNameOverlay.cs
  Content.Client/Administration/UI/SpawnExplosion/ExplosionDebugOverlay.cs
  Content.Client/Links/UILinks.cs
  Content.Client/NPC/HTN/HTNOverlay.cs
  Content.Client/NodeContainer/NodeVisualizationOverlay.cs
  Content.Client/Parallax/ParallaxControl.cs
  Content.Client/Stylesheets/StyleBase.cs
  Content.Client/Stylesheets/StyleNano.cs
  Content.Client/Stylesheets/StyleSpace.cs
  Content.Client/Suspicion/TraitorOverlay.cs
  Resources/Audio/Announcements/license.txt
  Resources/Audio/Announcements/welcome.ogg
  Resources/Fonts/Barlow/Barlow-Black.ttf
  Resources/Fonts/Barlow/Barlow-BlackItalic.ttf
  Resources/Fonts/Barlow/Barlow-Bold.ttf
  Resources/Fonts/Barlow/Barlow-BoldItalic.ttf
  Resources/Fonts/Barlow/Barlow-ExtraBold.ttf
  Resources/Fonts/Barlow/Barlow-ExtraBoldItalic.ttf
  Resources/Fonts/Barlow/Barlow-ExtraLight.ttf
  Resources/Fonts/Barlow/Barlow-ExtraLightItalic.ttf
  Resources/Fonts/Barlow/Barlow-Italic.ttf
  Resources/Fonts/Barlow/Barlow-Light.ttf
  Resources/Fonts/Barlow/Barlow-LightItalic.ttf
  Resources/Fonts/Barlow/Barlow-Medium.ttf
  Resources/Fonts/Barlow/Barlow-MediumItalic.ttf
  Resources/Fonts/Barlow/Barlow-Regular.ttf
  Resources/Fonts/Barlow/Barlow-SemiBold.ttf
  Resources/Fonts/Barlow/Barlow-SemiBoldItalic.ttf
  Resources/Fonts/Barlow/Barlow-Thin.ttf
  Resources/Fonts/Barlow/Barlow-ThinItalic.ttf
  Resources/Fonts/Barlow/License.txt
  Resources/Fonts/BarlowDisplay/BarlowDisplay-Bold.ttf
  Resources/Fonts/BarlowDisplay/BarlowDisplay-BoldItalic.ttf
  Resources/Fonts/BarlowDisplay/BarlowDisplay-Italic.ttf
  Resources/Fonts/BarlowDisplay/BarlowDisplay-Light.ttf
  Resources/Fonts/BarlowDisplay/BarlowDisplay-LightItalic.ttf
  Resources/Fonts/BarlowDisplay/BarlowDisplay-Regular.ttf
  Resources/Fonts/BarlowDisplay/License.txt
  Resources/Maps/frigid.yml
  Resources/Textures/Logo/logo.png
Labels: Changes: Map

#23 Updated the rules to fit MRP
  Resources/Server Info/Rules.txt
Labels: No C#

#25 Counter Storage, Map Update and Shotgun Buff
  Resources/Maps/frigid.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml
  Resources/Prototypes/Entities/Structures/Furniture/Tables/tables.yml
  Resources/Prototypes/Recipes/Construction/furniture.yml
  Resources/Prototypes/_Frigid/Catalog/Fills/Locker/counters.yml
  Resources/Prototypes/_Frigid/Entities/Markers/Spawners/Random/counter.yml
  Resources/Prototypes/_Frigid/Entities/Objects/Specific/Medical/pills.yml
Labels: Changes: Map, No C#

#29 New fills and counters
  Content.Client/Zombies/ZombieSystem.cs
  Content.Server/Zombies/ZombifyOnDeathSystem.cs
  Content.Shared/Zombies/ZombieComponent.cs
  Resources/Maps/frigid.yml
  Resources/Prototypes/Entities/Objects/Misc/tiles.yml
  Resources/Prototypes/Roles/Jobs/Civilian/reporter.yml
  Resources/Prototypes/Roles/Jobs/Science/chemist.yml
  Resources/Prototypes/Roles/Jobs/Science/scientist.yml
  Resources/Prototypes/Roles/Jobs/departments.yml
  Resources/Prototypes/Tiles/floors.yml
  Resources/Prototypes/Tiles/plating.yml
  Resources/Prototypes/_Frigid/Catalog/Fills/Locker/counters.yml
  Resources/Prototypes/_Frigid/Entities/Markers/Random/counter.yml
  Resources/Prototypes/_Frigid/Entities/Objects/Specific/Medical/pills.yml
Labels: Changes: Map

#34 Soldiers 1984
  Resources/Prototypes/_Frigid/Maps/frigid.yml
Labels: No C#

#36 new logo
  Resources/Textures/Logo/icon.ico
  Resources/Textures/Logo/icon/icon-128x128.png
  Resources/Textures/Logo/icon/icon-16x16.png
  Resources/Textures/Logo/icon/icon-24x24.png
  Resources/Textures/Logo/icon/icon-256x256.png
  Resources/Textures/Logo/icon/icon-32x32.png
  Resources/Textures/Logo/icon/icon-48x48.png
  Resources/Textures/Logo/icon/icon-64x64.png
  Resources/Textures/Logo/logo.png
  Resources/Textures/Logo/logo.svg
Labels: No C#

#54 Medical love
  Resources/Prototypes/Catalog/Fills/Items/firstaidkits.yml
  Resources/Prototypes/Catalog/Fills/Lockers/medical.yml
  Resources/Prototypes/Catalog/Research/technologies.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/medical.yml
  Resources/Prototypes/Entities/Objects/Specific/Medical/healing.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Labels: No C#

#53 Map fixes
  Resources/Maps/Shuttles/emergency_shuttle.yml
  Resources/Maps/centcomm.yml
  Resources/Maps/frigid.yml
  Resources/Prototypes/_Frigid/Parallaxes/snow.yml
Labels: Changes: Map, No C#

#56 Another Rain Plushie
  Resources/Prototypes/_Frigid/Entities/Objects/Fun/toys.yml
  Resources/Textures/_Frigid/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/_Frigid/Objects/Fun/toys.rsi/plushie_rain_maid.png
Labels: Changes: Sprites, No C#

#62 Fix incorrect shotgun gauge names
  Resources/Prototypes/Catalog/Fills/Boxes/ammunition.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/shotgun.yml
  Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Magazines/shotgun.yml
Labels: No C#

#63 Police uniforms will now actually be called police uniforms
  Resources/Prototypes/_Frigid/Entities/Clothing/Uniforms/jumpsuits.yml
Labels: No C#

#65 Music change + parallax
  Resources/Audio/Lobby/attributions.yml
  Resources/Audio/Lobby/flip-flap.ogg
  Resources/Audio/Lobby/flip-flap.txt
  Resources/Audio/Lobby/marhaba.ogg
  Resources/Audio/Lobby/space_asshole.ogg
  Resources/Audio/Lobby/taurium.ogg
  Resources/Audio/Lobby/thunderdome.ogg
  Resources/Audio/Lobby/title3.ogg
  Resources/Prototypes/Parallaxes/default.yml
  Resources/Prototypes/SoundCollections/lobby.yml
Labels: No C#

#64 Clean up prototypes
  Resources/Prototypes/_Frigid/Entities/Mobs/NPCs/zeds.yml
  Resources/Prototypes/_Frigid/Roles/Jobs/Civilian/farmer.yml
  Resources/Prototypes/_Frigid/Roles/Jobs/Civilian/prisoner.yml
  Resources/Prototypes/_Frigid/Roles/Jobs/Civilian/service_worker.yml
  Resources/Prototypes/_Frigid/Roles/Jobs/Engineering/mechanic.yml
  Resources/Prototypes/_Frigid/Roles/Jobs/Security/military.yml
Labels: No C#

#66 Airplane Shuttle
  Content.Server/Shuttles/Systems/ShuttleSystem.EmergencyShuttle.cs
  Resources/Maps/Shuttles/emergency_shuttle.yml
  Resources/Maps/centcomm.yml
  Resources/Maps/frigid.yml
Labels: Changes: Map

#72 More Random Spawners
  Resources/Prototypes/_Frigid/Entities/Markers/Random/Engineering/engineer.yml
  Resources/Prototypes/_Frigid/Entities/Markers/Random/Security/ammo.yml
  Resources/Prototypes/_Frigid/Entities/Markers/Random/Security/weapon.yml
Labels: No C#

#73 wood
  Resources/Prototypes/Entities/Structures/Walls/walls.yml
  Resources/Prototypes/Recipes/Construction/Graphs/structures/barricades.yml
  Resources/Prototypes/Recipes/Construction/Graphs/structures/girder.yml
  Resources/Prototypes/Recipes/Construction/structures.yml
Labels: No C#, Status: Needs Review

#74 Two new concrete walls
  Resources/Prototypes/_Frigid/Entities/Structures/Walls/walls.yml
  Resources/Textures/_Frigid/Structures/Walls/store.rsi/full.png
  Resources/Textures/_Frigid/Structures/Walls/store.rsi/meta.json
  Resources/Textures/_Frigid/Structures/Walls/store.rsi/store0.png
  Resources/Textures/_Frigid/Structures/Walls/store.rsi/store1.png
  Resources/Textures/_Frigid/Structures/Walls/store.rsi/store2.png
  Resources/Textures/_Frigid/Structures/Walls/store.rsi/store3.png
  Resources/Textures/_Frigid/Structures/Walls/store.rsi/store4.png
  Resources/Textures/_Frigid/Structures/Walls/store.rsi/store5.png
  Resources/Textures/_Frigid/Structures/Walls/store.rsi/store6.png
  Resources/Textures/_Frigid/Structures/Walls/store.rsi/store7.png
  Resources/Textures/_Frigid/Structures/Walls/superstore.rsi/full.png
  Resources/Textures/_Frigid/Structures/Walls/superstore.rsi/meta.json
  Resources/Textures/_Frigid/Structures/Walls/superstore.rsi/store0.png
  Resources/Textures/_Frigid/Structures/Walls/superstore.rsi/store1.png
  Resources/Textures/_Frigid/Structures/Walls/superstore.rsi/store2.png
  Resources/Textures/_Frigid/Structures/Walls/superstore.rsi/store3.png
  Resources/Textures/_Frigid/Structures/Walls/superstore.rsi/store4.png
  Resources/Textures/_Frigid/Structures/Walls/superstore.rsi/store5.png
  Resources/Textures/_Frigid/Structures/Walls/superstore.rsi/store6.png
  Resources/Textures/_Frigid/Structures/Walls/superstore.rsi/store7.png
Labels: Changes: Sprites, No C#

#75 Frigid Map Redesign
  Resources/Maps/frigid.yml
  Resources/Prototypes/_Frigid/Maps/frigid.yml
Labels: Changes: Map, No C#
